# Add 'repo' label to any root file changes
repo:
  - changed-files:
      - any-glob-to-any-file: "*"

# Add 'github-actions' label to changes in GitHub Actions-related files under the '.github' directory
# github-actions:
#   - changed-files:
#       - any-glob-to-any-file:
#           - .github/actions/*
#           - .github/actions/*/**
#           - .github/auto_assign.yml
#           - .github/auto_assign.yml/**
#           - .github/dependabot.yml
#           - .github/dependabot.yml/**
#           - .github/workflows/*
#           - .github/workflows/*/**

# Add 'github-actions-build' label to any changes in the 'build' directory
github-actions-build:
  - changed-files:
      - any-glob-to-any-file:
          - build/*
          - build/*/**

# Add 'github-actions-linux' label to any changes in the 'linux' directory
github-actions-linux:
  - changed-files:
      - any-glob-to-any-file:
          - linux/*
          - linux/*/**

# Add 'github-actions-package' label to any changes in the 'package' directory
github-actions-package:
  - changed-files:
      - any-glob-to-any-file:
          - package/*
          - package/*/**

# Add 'github-actions-macos' label to any changes in the 'macos' directory
github-actions-macos:
  - changed-files:
      - any-glob-to-any-file:
          - macos/*
          - macos/*/**
